"""Locator Inspector engine.

Given a page and one element on it, list every way Playwright could find that
element, and check each one on the live page: how many elements it matches, and
whether the first match is the element you meant.

Run from the terminal:
    python inspector.py https://www.saucedemo.com Login
    python inspector.py https://demoqa.com/automation-practice-form "#firstName" --css
"""

import json
import re
import sys
from dataclasses import dataclass, field

import errinshort  # adds a short "what broke, how to fix" card under any crash
from playwright.sync_api import Locator, Page, sync_playwright

# 2. READ — everything that might identify the element, read in the browser.
_SIGNALS_JS = """
el => {
  const attr = (n) => el.getAttribute(n);
  const testAttr = ['data-testid', 'data-test', 'data-test-id'].find((a) => el.hasAttribute(a)) || null;
  const parts = [];
  for (let n = el; n && n.nodeType === 1; n = n.parentElement) {
    let i = 1;
    for (let s = n.previousElementSibling; s; s = s.previousElementSibling) if (s.tagName === n.tagName) i++;
    parts.unshift(`${n.tagName.toLowerCase()}[${i}]`);
  }
  return {
    tag: el.tagName.toLowerCase(),
    id: attr('id'),
    name: attr('name'),
    test_attr: testAttr,
    test_id: testAttr ? attr(testAttr) : null,
    aria_label: attr('aria-label'),
    placeholder: attr('placeholder'),
    label: el.labels && el.labels.length ? el.labels[0].innerText.trim() : null,
    text: (el.innerText || '').trim().replace(/\\s+/g, ' ').slice(0, 80),
    classes: [...el.classList],
    xpath: '/' + parts.join('/'),
  };
}
"""


@dataclass
class Row:
    kind: str
    code: str  # the Playwright expression, ready to paste
    matches: int = 0
    is_target: bool = False
    generated: bool = False
    note: str = ""

    @property
    def status(self) -> str:
        if self.matches == 0:
            return "no match"
        if self.matches > 1:
            return f"ambiguous ({self.matches})"
        return "unique" if self.is_target else "different element"

    @property
    def ok(self) -> bool:
        return self.status == "unique"


@dataclass
class Report:
    url: str
    query: str
    found_via: str
    signals: dict
    role: str | None
    accessible_name: str | None
    rows: list[Row] = field(default_factory=list)
    screenshot: bytes = b""

    @property
    def best(self) -> Row | None:
        """The first unique locator, in priority order, that does not look generated."""
        return next((r for r in self.rows if r.ok and not r.generated), None)


def looks_generated(value: str) -> bool:
    """Does this id/class look like it was generated by a build tool?

    Digits at either end of a segment are an ordering convention (`04fullname`,
    `address1`); digits inside one, or a CSS-in-JS prefix, are a hash.
    """
    if re.match(r"^(css|sc|jss|emotion)-", value) or re.match(r"^react-[a-z-]*\d", value):
        return True
    for segment in re.split(r"[-_\s]+", value):
        core = segment.strip("0123456789")
        if len(segment) >= 5 and any(c.isdigit() for c in core):
            return True
    return False


def _q(value: str) -> str:
    """A double-quoted string literal, safe to paste into Python."""
    return json.dumps(value, ensure_ascii=False)


def _attr(value: str) -> str:
    """A CSS attribute value in single quotes, so it reads cleanly inside a
    double-quoted Python string: [data-test='login-button']."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _role_and_name(target: Locator) -> tuple[str | None, str | None]:
    """The role and accessible name Playwright computes, from its aria snapshot:
    a first line like `- button "Login"`."""
    match = re.match(r'^- (\w+)(?: "((?:[^"\\]|\\.)*)")?', target.aria_snapshot().strip())
    if not match:
        return None, None
    return match.group(1), match.group(2)


# 1. FIND
def find_target(page: Page, query: str, css: bool) -> tuple[Locator, str]:
    """The element you mean, and how it was found."""
    if css:
        attempts = [(f"css {query}", page.locator(query))]
    else:
        attempts = [
            ("button", page.get_by_role("button", name=query, exact=True)),
            ("link", page.get_by_role("link", name=query, exact=True)),
            ("label", page.get_by_label(query, exact=True)),
            ("placeholder", page.get_by_placeholder(query, exact=True)),
            ("text", page.get_by_text(query, exact=True)),
            ("text (partial)", page.get_by_text(query)),
        ]
    for how, locator in attempts:
        count = locator.count()
        if count:
            note = f" — {count} matched, using the first" if count > 1 else ""
            return locator.first, how + note
    raise LookupError(f"nothing on the page matches {query!r}")


# 3. BUILD
def build_rows(page: Page, s: dict, role: str | None, name: str | None) -> list[tuple[Row, Locator]]:
    rows: list[tuple[Row, Locator]] = []

    def add(kind: str, code: str, locator: Locator, value: str = "", note: str = "") -> None:
        rows.append((Row(kind, code, generated=bool(value) and looks_generated(value), note=note), locator))

    tag = s["tag"]
    if s["test_id"]:
        css = f"[{s['test_attr']}={_attr(s['test_id'])}]"
        add("test id", f"page.locator({_q(css)})", page.locator(css), s["test_id"])
    if s["id"]:
        css = f"[id={_attr(s['id'])}]"
        add("id", f"page.locator({_q('#' + s['id'])})", page.locator(css), s["id"])
    if s["name"]:
        css = f"{tag}[name={_attr(s['name'])}]"
        add("name", f"page.locator({_q(css)})", page.locator(css), s["name"])
    if role and name:
        add(
            "role + name",
            f"page.get_by_role({_q(role)}, name={_q(name)}, exact=True)",
            page.get_by_role(role, name=name, exact=True),
        )
        add(
            "role + name (partial)",
            f"page.get_by_role({_q(role)}, name={_q(name)})",
            page.get_by_role(role, name=name),
            note="without exact=True: also matches names that contain it",
        )
    if s["label"]:
        add("label", f"page.get_by_label({_q(s['label'])}, exact=True)", page.get_by_label(s["label"], exact=True))
    if s["placeholder"]:
        add(
            "placeholder",
            f"page.get_by_placeholder({_q(s['placeholder'])}, exact=True)",
            page.get_by_placeholder(s["placeholder"], exact=True),
        )
    if s["text"] and len(s["text"]) <= 60:
        add("text", f"page.get_by_text({_q(s['text'])}, exact=True)", page.get_by_text(s["text"], exact=True))
        add(
            "text (partial)",
            f"page.get_by_text({_q(s['text'])})",
            page.get_by_text(s["text"]),
            note="without exact=True: also matches text that contains it",
        )
    if s["classes"]:
        css = tag + "".join(f".{c}" for c in s["classes"][:3])
        add("css class", f"page.locator({_q(css)})", page.locator(css), " ".join(s["classes"][:3]))
    add(
        "xpath",
        f"page.locator({_q('xpath=' + s['xpath'])})",
        page.locator("xpath=" + s["xpath"]),
        note="positional: breaks when anything above it moves",
    )
    return rows


def _screenshot(page: Page, target: Locator) -> bytes:
    """A screenshot with the element outlined in red."""
    target.scroll_into_view_if_needed()
    target.evaluate("el => { el.dataset.liOutline = el.style.outline; el.style.outline = '3px solid red'; }")
    image = page.screenshot()
    target.evaluate("el => { el.style.outline = el.dataset.liOutline; delete el.dataset.liOutline; }")
    return image


def inspect(url: str, query: str, css: bool = False) -> Report:
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch()
        page = browser.new_page(viewport={"width": 1280, "height": 800})
        try:
            page.goto(url, wait_until="domcontentloaded")
            page.wait_for_timeout(1000)  # let client-side apps render

            target, found_via = find_target(page, query, css)
            signals = target.evaluate(_SIGNALS_JS)
            role, name = _role_and_name(target)
            report = Report(url, query, found_via, signals, role, name)

            # 4. CHECK — ask Playwright itself, so the counts are exactly its own.
            handle = target.element_handle()
            for row, locator in build_rows(page, signals, role, name):
                row.matches = locator.count()
                if row.matches:
                    row.is_target = locator.first.evaluate("(el, target) => el === target", handle)
                report.rows.append(row)

            report.screenshot = _screenshot(page, target)
            return report
        finally:
            browser.close()


def _print(report: Report) -> None:
    print(f"\n{report.url}  →  {report.query!r}  (found via {report.found_via})")
    print(f"role={report.role!r}  name={report.accessible_name!r}  tag={report.signals['tag']}\n")
    for row in report.rows:
        mark = "✅" if row.ok else "❌"
        flag = "  ⚠️ looks generated" if row.generated else ""
        print(f"{mark} {row.status:18} {row.kind:22} {row.code}{flag}")
    best = report.best
    print(f"\nbest: {best.code if best else 'none — no unique, stable locator'}")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    _print(inspect(sys.argv[1], sys.argv[2], css="--css" in sys.argv))
